---
# Source: zero-bin/templates/hull.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: leader
    app.kubernetes.io/instance: zero-bin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zero-bin
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: ""
    helm.sh/chart: zero-bin-1.0.0
  name: zero-bin-leader
  namespace: zkevm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: leader
      app.kubernetes.io/instance: zero-bin
      app.kubernetes.io/name: zero-bin
---
# Source: zero-bin/templates/hull.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: zero-bin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zero-bin
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: ""
    helm.sh/chart: zero-bin-1.0.0
  name: zero-bin-worker
  namespace: zkevm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: zero-bin
      app.kubernetes.io/name: zero-bin
---
# Source: zero-bin/templates/hull.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: immutable-prod-k8s@immutable-418115.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: default
    app.kubernetes.io/instance: zero-bin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zero-bin
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: ""
    helm.sh/chart: zero-bin-1.0.0
  name: zero-bin-default
  namespace: zkevm
---
# Source: zero-bin/templates/hull.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: default
    app.kubernetes.io/instance: zero-bin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zero-bin
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: ""
    helm.sh/chart: zero-bin-1.0.0
  name: zero-bin-default
  namespace: zkevm
---
# Source: zero-bin/templates/hull.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: default
    app.kubernetes.io/instance: zero-bin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zero-bin
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: ""
    helm.sh/chart: zero-bin-1.0.0
  name: zero-bin-default
  namespace: zkevm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zero-bin-default
subjects:
- kind: ServiceAccount
  name: zero-bin-default
---
# Source: zero-bin/templates/hull.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: leader
    app.kubernetes.io/instance: zero-bin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zero-bin
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: ""
    helm.sh/chart: zero-bin-1.0.0
  name: zero-bin-leader
  namespace: zkevm
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: leader
    app.kubernetes.io/instance: zero-bin
    app.kubernetes.io/name: zero-bin
  type: LoadBalancer
---
# Source: zero-bin/templates/hull.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: leader
    app.kubernetes.io/instance: zero-bin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zero-bin
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: ""
    helm.sh/chart: zero-bin-1.0.0
  name: zero-bin-leader
  namespace: zkevm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: leader
      app.kubernetes.io/instance: zero-bin
      app.kubernetes.io/name: zero-bin
  template:
    metadata:
      labels:
        app.kubernetes.io/component: leader
        app.kubernetes.io/instance: zero-bin
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: zero-bin
        app.kubernetes.io/part-of: undefined
        app.kubernetes.io/version: ""
        helm.sh/chart: zero-bin-1.0.0
      namespace: zkevm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - zk
      containers:
      - command:
        - coordinator
        env:
        - name: AMQP_URI
          valueFrom:
            secretKeyRef:
              key: amqp_uri
              name: rmq-credentials
        - name: ARITHMETIC_CIRCUIT_SIZE
          value: 16..23
        - name: BYTE_PACKING_CIRCUIT_SIZE
          value: 9..21
        - name: CPU_CIRCUIT_SIZE
          value: 12..25
        - name: KECCAK_CIRCUIT_SIZE
          value: 14..20
        - name: KECCAK_SPONGE_CIRCUIT_SIZE
          value: 9..15
        - name: LOGIC_CIRCUIT_SIZE
          value: 12..18
        - name: MEMORY_CIRCUIT_SIZE
          value: 17..28
        - name: PALADIN_AMQP_URI
          valueFrom:
            secretKeyRef:
              key: amqp_uri
              name: rmq-credentials
        - name: PALADIN_RUNTIME
          value: AMQP
        - name: RUST_LOG
          value: info
        - name: SERVER_ADDR
          value: 0.0.0.0:8080
        image: us.gcr.io/immutable-418115/zero-bin-leader:sha-123
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        name: leader
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 2
            memory: 6Gi
          requests:
            cpu: 1
            memory: 2Gi
      serviceAccountName: zero-bin-default
      tolerations:
      - effect: NoSchedule
        key: workload
        operator: Equal
        value: zk
---
# Source: zero-bin/templates/hull.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: zero-bin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zero-bin
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: ""
    helm.sh/chart: zero-bin-1.0.0
  name: zero-bin-worker
  namespace: zkevm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: zero-bin
      app.kubernetes.io/name: zero-bin
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/instance: zero-bin
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: zero-bin
        app.kubernetes.io/part-of: undefined
        app.kubernetes.io/version: ""
        helm.sh/chart: zero-bin-1.0.0
      namespace: zkevm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - zk
      containers:
      - env:
        - name: AMQP_URI
          valueFrom:
            secretKeyRef:
              key: amqp_uri
              name: rmq-credentials
        - name: ARITHMETIC_CIRCUIT_SIZE
          value: 16..21
        - name: BYTE_PACKING_CIRCUIT_SIZE
          value: 9..21
        - name: CPU_CIRCUIT_SIZE
          value: 12..23
        - name: KECCAK_CIRCUIT_SIZE
          value: 14..19
        - name: KECCAK_SPONGE_CIRCUIT_SIZE
          value: 9..15
        - name: LOGIC_CIRCUIT_SIZE
          value: 12..18
        - name: MEMORY_CIRCUIT_SIZE
          value: 17..25
        - name: RUST_BACKTRACE
          value: full
        - name: RUST_LOG
          value: info
        image: us.gcr.io/immutable-418115/zero-bin-pgo-worker:sha-123
        imagePullPolicy: Always
        name: worker
        resources:
          limits:
            cpu: 5
            memory: 32Gi
          requests:
            cpu: 5
            memory: 32Gi
      serviceAccountName: zero-bin-default
      tolerations:
      - effect: NoSchedule
        key: workload
        operator: Equal
        value: zk
